#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIyX/+NAB1zqh6agc8nn8179ZKDYpRqz1cqlTPxNsiax9LxABFWmwOrdQzH0ILZ31VEv4pVmGzbTsWBTC+hFmgZjNRd89IaJds9YLOjAeLDLHy+HG4B6IHjp8eSuE55vHwCvNg3fYEKhroNHhJ9AsjMgnNJcWNmRRFbJ3Y6cVXVy61S02+j+y72cUTNi9bd4KIKqFMyJkhpOcIST8vqgRNZmKWUZuwkU9pWe2JlQJiv7oLb6NdNKItt4ImqKIcNpc58n+hrkshRujLhnST8TPn1zHuvvWOjPtx+rNNvgJNfG0aXXBgQ3iHPFq+kx6z7CakggXFtm8PT1mRJaNNP04xAx677UxVwAH+SA0sBVDlmeWJWltEi9eI7/kPfv0QIatk3HGHHiBmNnYTjqSBgUEyYB3rGuvTkvC1EwYUSpKPY7mVSyYzzaEsKeD0NFWz3ghrGPRZ5XANIfMdq9tsZ/e2NCM66ZfQlZogojIefdgU0mvPTMMK9lCVdzRkQD0AICRqpB0cVkJZd1IjtuD7o9YA1ofcDDpORpButL1ifQ8xIWS7aedVNW39SiotRsdqy1AKwxplrKkUbyw+CFkdqWuLqjt9d59Ka7/7knAw2+rdbDBWgq+7CdMcH/0SM3LpdPATC1eFreHyQwXd2hj7og3ofLFmh7/X2tgXla8fuHdZ9w== root@pve01

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ca-certificates
  - curl
  - docker.io
  
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2
  
  # Enable Docker
  - systemctl enable docker
  - systemctl start docker

  # Create working directory
  - mkdir -p /opt/guacamole
  - cd /opt/guacamole

  # Create docker-compose.yml
  - |
    cat << 'EOF' > docker-compose.yml
# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd:1.6.0
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: guacamole_compose
    group_add:
      - "1000"
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRESQL_USERNAME: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole:1.6.0
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
## enable next line if not using nginx
##    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
    - 8080/tcp
    restart: always

########### optional ##############
  # nginx
  nginx:
   container_name: nginx_guacamole_compose
   restart: always
   image: nginx:latest
   volumes:
   - ./nginx/templates:/etc/nginx/templates:ro
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   ports:
   - 8443:443
   networks:
     - guacnetwork_compose
EOF

  # Start services
  - docker compose -f /opt/guacamole/docker-compose.yml up -d
