#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key
   
chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ca-certificates
  - curl
  - docker.io  
write_files:
  - path: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    permissions: '0644'
    content: |
      networks:
        guacnetwork_compose:
          driver: bridge
          
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  # Enable Docker
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable --now qemu-guest-agent
  # Start services
# - docker compose -f /opt/guacamole/docker-compose.yml up -d
