#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - default
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

package_update: true
package_upgrade: true

packages:
  - kali-desktop-xfce
  - lightdm
  - xorg
  - dbus-x11
  - openssh-server

runcmd:
  - systemctl enable ssh
  - systemctl enable lightdm
  - systemctl set-default graphical.target
