#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - kali-desktop-xfce
  - xorg
  - dbus-x11
  - openssh-server
  - tigervnc-standalone-server
  - tigervnc-common
  
write_files:
  - path: /home/kali/.vnc/xstartup
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh

      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      startxfce4 &
      
  - path: /etc/systemd/system/vncserver.service
    permissions: "0644"
    content: |
      [Unit]
      Description=TightVNC server on Port 5901
      After=Network.target
      
      [Service]
      Type=forking
      User=kali
      ExecStart=/usr/bin/vncserver -localhost=no -geometry 1280x720 :1
      ExecStop=/usr/bin/vncserver -kill :1
      
      [Install]
      WantedBy=multi-user.target

runcmd:
  - DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt install -y xfce4 xfce4-goodies xfce4-session kali-linux-default
  - systemctl enable ssh
  - systemctl set-default multi-user.target
  - mkdir -p /home/kali/.vnc
  - mkdir -p /home/kali/.config/tigervnc
  - chown -R kali:kali /home/kali
  - su - kali -c "printf 'password\npassword\n\n' | vncpasswd"
  - systemctl enable vncserver
  - systemctl start vncserver
